### ISSUE TITLE
小白的部署问题

### ISSUE THREAD

**Issue by Qve11** [yangSpica27/spica_weather_flutter#1]
大佬我在下载了你的源代码后尝试用as运行，但是theme.dart和database.g.dart会报错
下面是报错信息，我想问一下这怎么解决，谢谢！
![image](https://github.com/user-attachments/assets/eba963a7-6340-4f7a-87b1-204c077e9d89)

![image](https://github.com/user-attachments/assets/568891f6-9db0-4475-a5b3-38279b274e96)

**Comment by yangSpica27** [comment]
flutter版本不对吧 好像你这个版本的theme中都没这些属性
![QQ_1721973028615](https://github.com/user-attachments/assets/92dc0c47-e137-453d-a15f-1213ee6d8fa4)

**Comment by yangSpica27** [comment]
你试试看更新到最新flutterSDK版本后重新pub get后再运行

**Comment by Qve11** [comment]
更新fluttersdk得到解决了!但是database.g.dart仍旧报错
![image](https://github.com/user-attachments/assets/10828edf-91d1-40ea-abef-872604c8bc0f)
一开始以为是drift版本问题，卸载后重装依然报错，尝试下载spica_weather_flutter-2024-7-17，该版本代码成功运行！
![image](https://github.com/user-attachments/assets/46da94e8-8d7a-4a9b-9fc1-e2a492532e8a)

**Comment by yangSpica27** [comment]
更新Drift到最新版本，然后执行 dart run build_runner build 重新生成符合拉取的到的drift版本的 .g文件即可
