### ISSUE TITLE
非常好的项目,关于120hz首页滑动的顿挫感的问题

### ISSUE THREAD

**Issue by sanbei101** [yangSpica27/spica_weather_flutter#3]
**感谢**大佬的开源项目,于**首页**滑动时,相比原本的自带天气应用,`柠檬天气`在`120hz`下出现稍许**卡顿感**,想问问这是`flutter`的性能问题吗?
有没有优化的思路呢?

**Comment by yangSpica27** [comment]
原生这边我优化方案很多
1.利用idelHandler避免复杂绘制任务集中进行
2.不涉及Canvas的动画利用Hardware Layer缓存加速
3.使用HWTextureView/SurfaceView 用多线程进行绘制/计算
原生版本即使在不断的进行转场动画，且处于雨天效果【原生雨天效果是3000多个粒子/flutter仅为70个且没有流体碰撞效果】时，在我手机【小米13】上cpu也不会超过10%
但可惜的是，在Flutter这边这些优化方案都是不可用的
Flutter这边能做的，一个是开启Impeller【目前是未开启的】，会拥有更好的渲染性能，但是在部分机型上会出现花屏/文本渲染异常的问题，另外可以引入FltterSmooth【https://cjycode.com/flutter_smooth/】进行预渲染来降低瞬间的性能开销，这种方案我没有试过

**Comment by sanbei101** [comment]
感谢你的解答,但我在搜集资料时发现原因可能并不是这样,这似乎是新版Android引入的一个`电池省电`的刷新率调度问题

1. [关于Flutter应用无法达到90帧的问题](https://bbs.oneplus.com/thread/4795853?mod=viewthread&tid=4795853)

2. [我们收到了一加的官方解答](https://github.com/flutter/flutter/issues/35162#issuecomment-604761374)


> Folks, I have made a plugin as @liyuqian suggested. Implementation is quite rough. But gets things done in my OnePlus 7 Pro. Check it out in your device and let me know if it works and if I have missed anything.


Flutter针对这个问题设计了一个插件,或许能够解决这个问题:



[我们制作了一个插件来对帧率进行选择](https://github.com/flutter/flutter/issues/35162#issuecomment-609000841)

**Comment by yangSpica27** [comment]
如果是指刷新率被异常锁定的话，我这边也有复现过，小米会偶然的将应用的页面刷新了锁定在60hz，且在系统设置中提示为无法设置该应用刷新率，刷新率由应用接管无法手动指定【我编码中未作任何的锁定操作，且即使在原生部分使用wm相关的api指定preferredDisplayModeId为120hz的id也无法生效，你所提的插件本质上也就是调用该api】，我这边测试过的机型不多，有个oppo测试机是可以使用preferredDisplayModeId让应用锁定在设备所支持的最高刷新率运行的，但是小米是不可以的，重复安装多次应用，有时候默认情况下就是最高刷新率运行，有时又需要需要手动清除“电池和电量”和“joyse”应用的数据删除温控配置来解除60hz锁定（我确保我的设备温度/负载完全正常），这很让人迷惑，但是在另外的一批pixel设备上完全未发生过这种事情，我个人认为最终的原因还是国产ROM的魔改行为导致的，我开发者这边干预不了这些ROM的行为。
